update

diff --git a/bin/aurauto b/bin/aurauto
--- a/bin/aurauto
+++ b/bin/aurauto
@@ -3,17 +3,16 @@
 shopt -s extglob
 
 pkg="${PWD##*/}"
+(( $# > 0 )) && pkg="$1"
 
-if (( $# > 0 )); then
-  pkg="$1"
-  if [[ -d "$HOME/code/pkgBUILDs/$pkg" ]]; then
-    cd "$HOME/code/PKGBUILDs/$pkg"
-  elif [[ -d "$HOME/code/pkgBUILDs/$pkg-git" ]]; then
-    cd "$HOME/code/PKGBUILDs/$pkg-git"
-  else
-    printf "couldn't find PKGBUILD directory, abort...\n"
-    exit 1
-  fi
+if [[ -d "$HOME/code/PKGBUILDs/$pkg" ]]; then
+  cd "$HOME/code/PKGBUILDs/$pkg"
+elif [[ -d "$HOME/code/PKGBUILDs/$pkg-git" ]]; then
+  cd "$HOME/code/PKGBUILDs/$pkg-git"
+  pkg="$pkg-git"
+else
+  printf "couldn't find PKGBUILD directory, abort...\n"
+  exit 1
 fi
 
 makepkg -c --nobuild
@@ -22,6 +21,7 @@ burp *.src.tar.gz
 rm -rf !(PKGBUILD|*.install|*.patch)
 
 cd ..
+git pull -u origin master
 git add "$pkg"
 git commit -m "$pkg: updated"
 git push -u origin master
